### ISSUE TITLE
TypeError: Cannot read property 'normalModuleFactory' of undefined

### ISSUE THREAD

**Issue by twclark0** [GoogleChromeLabs/worker-plugin#1]
Getting this issue when trying to run webpack after installing the package and adding it to the plugins. Referencing this function `compiler.hooks.normalModuleFactory.tap`

Webpack version 3.1.0
Webpack-dev-server 2.7.1

Not sure if that is enough context or not.

**Comment by developit** [comment]
Hello! This plugin currently requires Webpack 4+.

**Comment by sdougbrown** [comment]
I misunderstood the webpack 4 requirement based on the peer deps in the project's package.json.  Thanks for clarifying.

**Comment by ctf0** [comment]
@developit 

https://github.com/GoogleChromeLabs/worker-plugin/blob/7706c013d59378cda76eb1e9922f07af945fe7f1/package.json#L79

so v3 should work

**Comment by developit** [comment]
Apologies, I'd incorrectly indicated webpack@3 compatibility there.  If anyone really needs webpack 3 support, it's been fixed.

**Comment by skaraman** [comment]
Can't figure out what I'm doing wrong here...

```
λ npm run dev

> svgproto@0.0.0 dev C:\Users\[...]\svgproto
> preact watch

TypeError: Cannot read property 'normalModuleFactory' of undefined
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svgproto@0.0.0 dev: `preact watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svgproto@0.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\[...]\AppData\Roaming\npm-cache\_logs\2019-07-11T06_17_26_947Z-debug.log

C:\Users\[...]\svgproto (master -> origin)
λ npm list webpack
svgproto@0.0.0 C:\Users\[...]\svgproto
+-- preact-cli@2.2.1
| `-- UNMET DEPENDENCY webpack@3.12.0
`-- webpack@4.35.3

npm ERR! missing: webpack@3.12.0, required by preact-cli@2.2.1

C:\Users\[...]\svgproto (master -> origin)
λ yarn list webpack
yarn list v1.16.0
warning Filtering by arguments is deprecated. Please use the pattern option instead.
├─ preact-cli@2.2.1
│  └─ webpack@3.12.0
└─ webpack@4.35.3
Done in 0.79s.
```

**Comment by emps** [comment]
so what the solution for this ?

**Comment by j-funk** [comment]
Looks like you need to upgrade webpack.
