### ISSUE TITLE
Other webpack plugins are executed twice although it is not necessary

### ISSUE THREAD

**Issue by 3846masa** [GoogleChromeLabs/worker-plugin#16]
## Problem

Because of #14, other webpack plugins are executed twice. However, many plugins are not necessary to run twice. (e.g. `html-webpack-plugin`, `clean-webpack-plugin`)

In my case, `@wasm-tool/wasm-pack-plugin` and `clean-webpack-plugin` cannot be used together.
`@wasm-tool/wasm-pack-plugin` build wasm file before bundling scripts, but `clean-webpack-plugin` clean twice before and after running `@wasm-tool/wasm-pack-plugin`, so wasm file will be removed when bundling.

I think, how about setting plugins as an option like below?

```js
[
  new WorkerPlugin({
    plugins: [new SomePluginInWorker()],
  }),
]
// Or
[
  new SomePluginInWorkerAndBrowser(),
  new WorkerPlugin({
    plugins: ['SomePluginInWorkerAndBrowser'],
  }),
]
```

**Comment by developit** [comment]
Released as [3.0.0](https://github.com/GoogleChromeLabs/worker-plugin/releases/tag/3.0.0)! Thanks so much @3846masa!
