### ISSUE TITLE
MIME type checking error

### ISSUE THREAD

**Issue by bfang711** [GoogleChromeLabs/worker-plugin#21]
When I am trying the latest release in Chrome 73. I get the following error.
``
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.`` at the beginning 1st line of the worker.jsx file.

in the main.jsx file I have 

>

> const worker = new Worker('./worker.jsx',{type:"module"}); 
 >   worker.onmessage = event=>{
 > 	       console.log("WORKER response: ",event.data);
  >    	};
>	worker.postMessage(0);

   

In the worker.jsx file, I have 
>   import answer from './answer';
 >   self.addEventListener('message',function(e){
  >         self.postMessage("123 123 abc abc");
  >  });

In answer.js file I have 
>   export default () => 42;

Can you please let me know what the issue is with MIME type and how can I fix it?

thank you

**Comment by 1234WoodMan** [comment]
hello, i encounter the same problem, how did you solve the issue? can you give me some suggestion？ thx!!

**Comment by xavism** [comment]
Up, I have the same mistake 

```javascript
    const minerWorker = new Worker('./../workers/worker.js', { type: 'module'})
```

```javascript
  import Helper from './../helpers'

  onmessage = (e) => {
      console.log('Worker: Message received from main script');
      Helper.doSomething()
      postMessage(e);
  };
```
