### ISSUE TITLE
Trailing Comma in the LoaderOption causes SyntaxError on removing `type:module`

### ISSUE THREAD

**Issue by lacolaco** [GoogleChromeLabs/worker-plugin#25]
At first, I think this is not only by the WorkerPlugin's implementation. 

## Problem

When `{type: 'module'}` contains trailing-comma like below, compiled JavaScript is broken.

```js
// pre-compile
new Worker('./foo.js', { 
  type: 'module',
});
```

```js
// post-compile
new Worker('./foo.js', { 
  , // <--- SyntaxError
});
```

## Workaround

Removing the comma.

```js
 new Worker('./foo.js', { type: 'module' });
```

## Version

I confirm reproducing in v3.0.0 and v3.1.0.

**Comment by lacolaco** [comment]
This can happen frequently if developers are using code formatter like Prettier.

**Comment by developit** [comment]
ooof! good catch.

**Comment by ViceIce** [comment]
the same is happen if you use additional options like:
``` typescript
new Worker('./monaco-css.worker', { type: 'module', name: 'monaco-css' });
```

**Comment by developit** [comment]
@ViceIce preserving `{type:'module'}` forces the worker code into strict mode by default, which is unexpected given it's being used to load CommonJS webpack output. I believe there are also environments in which `{ type: 'module' }` throws when passed to `Worker()`.

**Comment by developit** [comment]
If anyone has a deep working knowledge of Webpack's funky parser modifiers, this is the line that replaces `type:'module'` with an empty expression. Maybe it needs to be `null`? I have no idea.
https://github.com/GoogleChromeLabs/worker-plugin/blob/master/src/index.js#L79
