### ISSUE TITLE
Creating a Worker using a URL string

### ISSUE THREAD

**Issue by jslegers** [GoogleChromeLabs/worker-plugin#26]
I'm currently have a WebWorkerPool module, where a worker is created based on a URL string that is passed as a variable :

    this._worker = new Worker(this._script, { type: 'module' });

Is seems this plugin only supports string literals as a URL. 

Is there a way around this?

**Comment by developit** [comment]
No, there is no way around this. The URL is a module path, so it must be static at build time to allow bundling. One option that might work for your use-case would be to accept a Worker factory instead of a script URL:

```js
class WorkerPool {
  constructor(workerFactory) {
    this.factory = workerFactory;
  }
  allocate() {
    this._worker = this.factory();
  }
}

const pool = new WorkerPool( () => new Worker('./worker', { type: 'module' }) );
```

This avoids coupling a library to a specific Webpack plugin.
