### ISSUE TITLE
Support Shared Workers?

### ISSUE THREAD

**Issue by logankp** [GoogleChromeLabs/worker-plugin#29]
Could this plugin be enhanced to support Shared Workers?

**Comment by developit** [comment]
I don't have the time to add support for them, but I'd be happy to review a PR for it.

**Comment by stutrek** [comment]
I have added this with https://github.com/GoogleChromeLabs/worker-plugin/pull/42

**Comment by developit** [comment]
#42 is merged and will be released shortly!
