### ISSUE TITLE
Crashes when using ECMAScript modules

### ISSUE THREAD

**Issue by kdex** [GoogleChromeLabs/worker-plugin#38]
### What?
`.mjs` crashes during runtime.
### Why?
[Hard-coded value](https://github.com/GoogleChromeLabs/worker-plugin/blob/8dadf08b1cfbf5db8aa27b49d9b4ab7f4c42785e/src/index.js#L72).

## Detailed description
Webpack differentiates between actual ECMAScript modules (`.mjs`) and regular scripts (`.js`) in CommonJS style. For the uninitiated, CommonJS uses the global `require`¹ function while ECMAScript modules don't.

Apart from gaining some better static analysis (e. g., webpack emitting warnings when you're trying to import a non-existing export and corrected import semantics), using true ECMAScript modules also removes the CommonJS `require` function [which has been hard-coded into `worker-plugin`](https://github.com/GoogleChromeLabs/worker-plugin/blob/8dadf08b1cfbf5db8aa27b49d9b4ab7f4c42785e/src/index.js#L72), rather unfortunately.

As ECMAScript modules are the intended way forward, it'd be nice if support for them could be added as well. For now, code that tries to use ECMAScript modules will just crash on the following:

```
Uncaught ReferenceError: require is not defined
```

¹ To add to the confusion, even if it looks like you're using ECMAScript modules, because you can already write `import` and `export` thanks to your transpiler, you aren't actually using the semantics of ECMAScript modules, as those get transpiled into `require` before webpack touches them.

**Comment by developit** [comment]
Hiya! I finally managed to get this working (took me almost 8 hours 😬). It'll be in a 4.0.0 release shortly.

**Comment by kdex** [comment]
> took me almost 8 hours :grimacing:

Oh, wow. Who would have thought that one would have to dig so deep? :) But still, those are really amazing news. Thanks so much for working on this! :tada:
