### ISSUE TITLE
Documentation needs updating

### ISSUE THREAD

**Issue by jzombie** [GoogleChromeLabs/worker-plugin#41]
Digging around some of the issues here, it seems that there are more options available than what's in the README.md.

Also, there should be clarification that if you pass a variable, instead of a hardcoded string, into the Worker call, that it will not be picked up by the WebPack compilation, and will use the browser's native implementation w/o module compilation.

**Comment by developit** [comment]
These would both be great additions to the documentation. The latter is noted during compilation as an error/warning, but I don't think it's surfaced properly in the docs.

**Comment by developit** [comment]
Sorry for the delay, finally got around to updating the readme!
