### ISSUE TITLE
Cannot read property 'normalModuleFactory' of undefined

### ISSUE THREAD

**Issue by 873550602** [GoogleChromeLabs/worker-plugin#44]
I configured the WorkerPlugin plugin in my vue project, and the result project could not be started. The error message is: "Cannot read property normalModuleFactory of undefined"

**Comment by developit** [comment]
Hi @873550602 - can you tell me what version of Webpack this would be using? WorkerPlugin requires Webpack 4+.

**Comment by developit** [comment]
Closing as this is almost certainly just unsupported usage with Webpack 3.x.
