### ISSUE TITLE
Typescript support?

### ISSUE THREAD

**Issue by corbanbrook** [GoogleChromeLabs/worker-plugin#56]
Is there typescript support planned?

**Comment by developit** [comment]
In what sense? This should just use your existing TypeScript confguration.

**Comment by SimmeNilsson** [comment]
My guess would be question comes from older lib.dom.d.ts and lib.webworker.d.ts only specifying one argument to Worker constructor?
https://github.com/microsoft/TypeScript/commit/40bd7c89abbdf79493e2ea20dd80d9eb657dc82e#
If I'm not mistaken, it seems to be 3.1 and earlier.

**Comment by developit** [comment]
I'm going to close this one out - from what I can tell, TypeScript's `dom.d.ts` has supported `WorkerType` for at least 2 years.
