### ISSUE TITLE
how to change directory of worker?

### ISSUE THREAD

**Issue by stephenjason89** [GoogleChromeLabs/worker-plugin#71]
im using laravel mix and by default it places the file at public directory

here's my webpack Config

  `  .webpackConfig({
        plugins: [
            new WorkerPlugin({
                filename: '[name].worker.js'
            })
        ],
    });`

if i use the output 

`        output: {
            path: path.join(__dirname, 'public/js/workers'),
        },`

It places all my files there including my app.js which i don't want

Thank you for the help

**Comment by developit** [comment]
I believe this should work without any configuration:

```js
new Worker("./calculate-primes.js", {
  type: "module",
  name: "workers/calculate-primes",
});
```

FWIW this plugin will use `output.chunkFilename` if you define it:

```js
output: {
  path: path.join(__dirname, 'public/js'),
  filename: '[name].js',
  chunkFilename: 'chunks/[name].js',  // <-- public/js/chunks/calculate-primes.worker.js
},
```

**Comment by stephenjason89** [comment]
Thank you sir.
