### ISSUE TITLE
Question: New Worker Inside Loop Continuously Requests Script?

### ISSUE THREAD

**Issue by jfuehner** [GoogleChromeLabs/worker-plugin#72]
Curious if there is a more appropriate way to use the worker-plugin inside a loop? What I'm seeing is on every iteration the browser reloads the `./worker.js` file on each `new Worker`...

Say I have something like inside a loop...

```
     const worker = new Worker('./worker.js', { type: 'module' });
     const wrapper = Comlink.wrap(worker);
     const proxy = await new proxy();

    results.push(await proxy.data);     

    await proxy[Comlink.releaseProxy]();
    await worker.terminate();
```

Having the browser continuously request the same `./worker.js` file seems inappropriate. Ideally I would request the script once and be able to simply create new/multiple workers with the same script. I'm sure I am doing something wrong...

**Comment by developit** [comment]
The script is only re-requested if your headers require it to be, same as any HTTP resource. If you're testing this with DevTools open, make sure you don't have caching disabled otherwise any usage of a resource will trigger a re-fetch.

**Comment by developit** [comment]
Closing this out since it's likely working-as-designed (caching fixes it, use caching).
