### ISSUE TITLE
Any support for Webpack 3?

### ISSUE THREAD

**Issue by Jusmaar** [GoogleChromeLabs/worker-plugin#83]
I have this problem: :( 

TypeError: Cannot read property 'normalModuleFactory' of undefined

**Comment by developit** [comment]
Sorry, this project currently requires webpack 4. If you want to PR it, I would be happy to review. Just requires adding helpers [like these ones](https://github.com/developit/workerize-loader/blob/111e17a4e41c1d1322f4818f9267d1a5d7a585a4/src/index.js#L13-L32) in the following locations:

https://github.com/GoogleChromeLabs/worker-plugin/blob/f7b576f35557da1c399cdbc3a1eeea45c14ea81c/src/index.js#L39

https://github.com/GoogleChromeLabs/worker-plugin/blob/f7b576f35557da1c399cdbc3a1eeea45c14ea81c/src/index.js#L41-L43

https://github.com/GoogleChromeLabs/worker-plugin/blob/f7b576f35557da1c399cdbc3a1eeea45c14ea81c/src/index.js#L140-L145
