### ISSUE TITLE
vue use work-plugin. Error

### ISSUE THREAD

**Issue by cwwjsyc** [GoogleChromeLabs/worker-plugin#90]
in xxx.work.js has some code like:
```
(async function Loop() {
    self.setInterval(async () => {
        let data = 'abcdefg';
        postMessage(data);
    }, 3000)
})()
```

and then.  error on console. when compile like:
---------------------------------------------------------------------------------
```
    6:47  error  'regeneratorRuntime' is not defined         no-undef
   7:12  error  'regeneratorRuntime' is not defined         no-undef
   8:14  error  Unexpected constant condition               no-constant-condition
  11:76  error  'regeneratorRuntime' is not defined         no-undef
  13:22  error  'regeneratorRuntime' is not defined         no-undef
  14:24  error  Unexpected constant condition               no-constant-condition
  20:21  error  Expected a 'break' statement before 'case'  no-fallthrough
  28:11  error  Expected a 'break' statement before 'case'  no-fallthrough
```

but without Method 'setInterval' ,it can works.

**Comment by cwwjsyc** [comment]
Add code comment on the file of  *worker.js. like
`
/* eslint-disable */`

IT works.!

**Comment by cwwjsyc** [comment]
Thanks , it  was really working.

**Comment by kamaladenalhomsi** [comment]
the same issue for me, any help please?

**Comment by kamaladenalhomsi** [comment]
You can notice that the injected code is above the /* eslint-disable */ so I guess that's why it's not working

![image](https://user-images.githubusercontent.com/16209653/98258784-f6692a80-1f89-11eb-8768-3de57b9a3b87.png)

**Comment by mima3** [comment]
I created an .eslintignore file to work around this issue.
