### ISSUE TITLE
Failed to using 'importScripts' on *worker.js 

### ISSUE THREAD

**Issue by cwwjsyc** [GoogleChromeLabs/worker-plugin#91]
Vue Cli . I want use put some utility methos(e.g fetch  indexeddb ...) in a tool.js 
And then use self.importScipts  add tool.js to *worker.js. but have error like:
`Uncaught TypeError: Failed to execute 'importScripts' on 'WorkerGlobalScope': Module scripts don't support importScripts().`

**Comment by LifeIsStrange** [comment]
@cwwjsyc what solved your issue?
