### ISSUE TITLE
ESLint errors for code injected by Babel

### ISSUE THREAD

**Issue by jcestibariz** [GoogleChromeLabs/worker-plugin#95]
I'm using Babel with `preset-env` for IE support (sad, I know), and I'm getting these errors:

```
/.../TestWorker.js
  4:3   warning  Unexpected var, use let or const instead  no-var
  5:29  warning  Unexpected function expression            prefer-arrow-callback
  8:7   warning  Expected property shorthand               object-shorthand
 10:12  warning  Unexpected function expression            prefer-arrow-callback
 13:7   warning  Expected property shorthand               object-shorthand
```
The warnings seem to be about code that would be injected by Babel, but ESLint runs with `enforce: pre`, so looks like double processing. This happens only for the worker the rest of the code is built correctly.

Here's the (simplified) code for my worker:

```javascript
import process from './process';

self.onmessage = ({data}) =>
	process(data)
		.then(result => postMessage({type: 'success', result}))
		.catch(error => postMessage({type: 'error', error}));
```

This could be related to the problem reported in #86.

**Comment by kamaladenalhomsi** [comment]
+1

**Comment by dohun-toss** [comment]
I think you should add that file in `.eslintignore`

**Comment by jcestibariz** [comment]
@dohun-toss I'm sorry that's not acceptable. I need to lint my worker.

**Comment by dohun-toss** [comment]
@jcestibariz Are you using `eslint-loader`? I think you want to use `enforce: pre` option.
But, if you can give up `enforce: pre` option, there is alternative `eslint-webpack-plugin`

**Comment by dohun-toss** [comment]
```js
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: ['babel-loader', 'eslint-loader'], // without enforce pre, you can use lint first
      },
    ],
  },
  // ...
};
```

**Comment by jcestibariz** [comment]
@dohun-toss I had not noticed that `eslint-loader` was deprecated. Using `eslint-webpack-plugin` fixed the problem, thank you!
